### ISSUE TITLE
Kills In Current Targets

### ISSUE THREAD

**Issue by NoFoolLikeOne** [canonn-science/CAPIv2-Strapi#102]
This is shown on the website. Its a bit of an odd one as it is live stats we would need to update fairly frequently but it is also time bounded as we are only looking at kills in the current tick Thursday to Thursday for specific systems.

I think we actually need an eagle eye model to make this work

![Kills in Current Targets](https://docs.google.com/spreadsheets/d/e/2PACX-1vR8J04FrEoJ_a4nPI6rIyIsH2X41iQmICUaxK_SwdvL8PVq1-CBDynCF1vo3oFNM5krjwotkaIrH5Al/pubchart?oid=1091672444&format=image)

**Comment by derrickmehaffy** [comment]
Will need to speak to Fact on eagle eye data as I am not familiar with it to build a model

**Comment by NoFoolLikeOne** [comment]
The Eagle Eye data is all me I'm afraid.

https://docs.google.com/spreadsheets/d/1v-eNh7hjH9HRefysBcbqtGGg5U1y9VxpHepKrh_7EE4/edit?usp=sharing

What we would need to do is aggregate kills, grouped by system name and week on a Thursday boundary.

Then we need a table telling us that week x = has targets y and z so we 

Maybe something simple like 

week | target1 | kills1  | target2 | kills2
----| ------- |-------|---------|-------
4 | Lunguni | 855 | Mentor| 344 
5 |LTT 11383| 1  | Madngeri| 710 
6 |32 c Piscium| 0  | Kunuvi| 0 

Then we run a job to update the kill count for the current week every 10 minutes.

But we would also need a top ten list for each system as well

**Comment by derrickmehaffy** [comment]
No longer required, we don't really track targets anymore
