### ISSUE TITLE
Thargoid Glyph Survey

### ISSUE THREAD

**Issue by NoFoolLikeOne** [canonn-science/CAPIv2-Strapi#104]
On the USS Survey this is done as part of the USS drop manual data entry. In the new plugin this should be a popup interface that comes up after a scan. Something involving clicking on icons to identify the glypgh

We should get the icons from the valkunut page. 

It would be handy to detect a screengrab  and allow the user to upload an cropped image,

**Comment by derrickmehaffy** [comment]
Request is to add a model for uploading Thargoid Glyphs

Added to my To-Do

**Comment by NoFoolLikeOne** [comment]
Should probably have a think about how this interacts with Valknut. 

Should we have the glyph types listed in strapi or should valknut be the master? 
The EDMC plugin will need to get the icons from somwhere.

**Comment by derrickmehaffy** [comment]
Closing for now as not a priority
