### ISSUE TITLE
Thargoid Composition Survey

### ISSUE THREAD

**Issue by NoFoolLikeOne** [canonn-science/CAPIv2-Strapi#105]
Currently after a NHSS drop the user is presented with an interface that allows the to display the number and composition of thargoids in the instance. 

This will require a Strapi Model

It would be useful to be able to configure the interface from the server side so that new Thargoid types can be added quickly

The data can be used for a new map that can show the location of scouts vs interceptors and not just the threat levels

**Comment by derrickmehaffy** [comment]
Request is to add a NHSS report model that should tie into the USS model.

We can add a related model for types and allow public additions (though I would rather not) if this data can be grabbed from the journal then we can just a regular string field. If not we will need to add the related type model.

**Comment by NoFoolLikeOne** [comment]
This data cannot be grabbed from the journal. It has to be captured from user input

**Comment by NoFoolLikeOne** [comment]
I think that this is now obsolete, we no longer need to capture this information so dropping for CAPI
