### ISSUE TITLE
Apiupdate "UpdateTime" model typo.

### ISSUE THREAD

**Issue by coldwhitelight** [canonn-science/CAPIv2-Strapi#118]
In APIUPDATE model change:

```
"UpdateTime": {
      ...
},
```

to 

```
"updateTime": {
     ...
},
```

(first letter uppercase to first letter lowercase) for consistency with other fields.

**Comment by derrickmehaffy** [comment]
will modify it tonight

**Comment by derrickmehaffy** [comment]
Fixed in v2.0.18
