### ISSUE TITLE
Modify "apiupdate" model.

### ISSUE THREAD

**Issue by coldwhitelight** [canonn-science/CAPIv2-Strapi#122]
Request to modify 'apiupdate' model, in line with: https://github.com/canonn-science/CAPIv2-Updater/issues/22

- Remove forced:boolean field (It has been moved to updateLog)
- Add error:boolean field, determining if the update crashed or ended successfuly.

**Comment by derrickmehaffy** [comment]
Have started working on this: 9dbc82e577225bc8cee44d0abdf328fffe6cc229

**Comment by derrickmehaffy** [comment]
Completed
