### ISSUE TITLE
Strapi Paging Broken on Admin Screens

### ISSUE THREAD

**Issue by NoFoolLikeOne** [canonn-science/CAPIv2-Strapi#131]
**Which Server are you experencing the issue with:**

- [ ] Live Server - https://api.canonn.tech

- [ ] Beta Server - https://api.canonn.tech:2053

- [X] Alpha Server - https://api.canonn.tech:2083

**What endpoint(s) are you seeing the error on:**

URL: https://api.canonn.tech:2083/admin/plugins/content-manager/reportfss?source=content-manager

**Describe the problem in as much detail as possible:**

Unable to page through the data.

**Steps to reproduce the error:**
1. Go to reportfsses
2. Click on the paging controls at the bottom right of the page

**Additional context**

The problem is the new ? button on the bottom right corner. It is covering the controls so you cant navigate. Opening the DOM editor in firefox I was able to delete the button and with that out of the way I was able to page through the data

**Comment by derrickmehaffy** [comment]
Already being fixed: https://github.com/strapi/strapi/pull/3029

Will probably be in the next Strapi version, no ETA for now you can increase the amount per page (bottom left) and edit the URL to change page numbers.

**Comment by derrickmehaffy** [comment]
Fixed in v2.0.25
