### ISSUE TITLE
USS Survey

### ISSUE THREAD

**Issue by NoFoolLikeOne** [canonn-science/CAPIv2-Strapi#97]
The survey in the Canonn plugin will log USS drops but will also allow logging of USS from supercruise without drops.  

USS Drops can be marked as confirmed however supercruise reports are manual and therefore considered suspect. 

We could use USS drop data to prove that the type and threat level are valid combinations and request confirmation if it is in any way suspect.

Counts of USS types/threat are not important.

We will need to update the strapi model with appropriate statuses and we will need a mechanism for validating manual submissions.

Also keeping track of the time spent in supercruise would be useful for the perspective of Hrafnagud which needs to know if a system has been surveyed to count it as complete.

**Comment by derrickmehaffy** [comment]
How useful is the data on USS from supercruise? Realistically I don't see any benefit, and would be difficult to "validate" as they are non-static

**Comment by derrickmehaffy** [comment]
Decided to remove normal USS in favor of NHSS
